### PR TITLE
Fixed Bug

### PR DESCRIPTION
**Pull request by itsMeShon**
## Fixed Bugs

I found a small bug wjile checking the actions. Its was just a simple mistake with the variable spelling of your code.

- [X] Fixed Variable error

### CODE REVIEW

**Comment by pranavbaburaj** [comment]
Thanks for the contribution. much appreciated :)

**Review by pranavbaburaj — APPROVED** [review]
Thanks for the contribution. much appreciated :)

**Comment by itsMeShon** [comment]
Welcome!

**Comment by shonsanthosh** [comment]
Can u follow me? @pranavbaburaj

**Pull request merged**
